# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Tests

on:
  push:
    branches: ["master", "CI"]
  pull_request:
    branches: ["master"]

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Spin up ImmuDB container
        run: |
          docker network create immudbnet
          docker run -d --net immudbnet -it --rm --name immudb -p 3322:3322 codenotary/immudb:latest

      - name: Set up Env Vars
        run: |
          # TODO: when not default passwords; use secrets for these
          arr=( 'IMMUDB_PASSWORD=immudb' 'IMMUDB_USER=immudb' 'IMMUDB_DB_NAME=defaultdb');
          printf '%s\n' "${arr[@]}" >> .env

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
